### ISSUE TITLE
Premier dépôt ne compile pas

### ISSUE THREAD

**Issue by KirmTwinty** [KirmTwinty/uge-beamer#6]

**Comment by romain-noel** [comment]
C'est quoi le message d'erreur ? C'est peut-être une histoire de config car chez moi ça tourne ! 

Petite précision il faut ajouter l'option de compilation -shell-escape pour le package glossaries, et compiler 2 fois (la première donne un message d'erreur du style aritmetic overflow, mais il ne faut pas en tenir compte).

**Comment by romain-noel** [comment]
Il semblerait que cela soit une forme de bug d'interaction entre `\usepackage{appendixnumberbeamer}` et `\usetheme{metropolis}`. Donc pas vraiment de notre faute. Et visiblement il y a deux solutions: 1) éviter le problème en ne créant pas de `\section` dans l'`\appendix` 2) si l'on veut vraiment des `\section` dans l'`\appendix`, alors il faut compiler deux fois, en ne tenant pas compte des erreurs lors de la première compilations.

**Comment by romain-noel** [comment]
je pense que tu peux fermé le problème.
